
namespace DESIGNER.Reportes
{
	partial class frmCentro
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle15 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle16 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCentro));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.gridCentroVac = new System.Windows.Forms.DataGridView();
            this.gridTipoCentro = new System.Windows.Forms.DataGridView();
            this.lblTipoCentro = new System.Windows.Forms.Label();
            this.lblCentrosVac = new System.Windows.Forms.Label();
            this.btnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblTotalCentros = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnCancelarTipoC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEliminarTipoC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModificarTipoC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRegistrarTipoC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.cboCamposFiltrar = new System.Windows.Forms.ComboBox();
            this.txtFiltrar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnExpExcel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.lblTotalRegistroTipoC = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.gridCentroVac)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridTipoCentro)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // gridCentroVac
            // 
            this.gridCentroVac.AllowUserToAddRows = false;
            this.gridCentroVac.AllowUserToDeleteRows = false;
            this.gridCentroVac.AllowUserToResizeColumns = false;
            this.gridCentroVac.AllowUserToResizeRows = false;
            this.gridCentroVac.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.gridCentroVac.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(34)))), ((int)(((byte)(51)))));
            this.gridCentroVac.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridCentroVac.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.gridCentroVac.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle13.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle13.BackColor = System.Drawing.Color.SteelBlue;
            dataGridViewCellStyle13.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle13.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(215)))), ((int)(((byte)(225)))), ((int)(((byte)(242)))));
            dataGridViewCellStyle13.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            dataGridViewCellStyle13.SelectionBackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            dataGridViewCellStyle13.SelectionForeColor = System.Drawing.SystemColors.Desktop;
            dataGridViewCellStyle13.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.gridCentroVac.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle13;
            this.gridCentroVac.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.gridCentroVac.EnableHeadersVisualStyles = false;
            this.gridCentroVac.Location = new System.Drawing.Point(61, 353);
            this.gridCentroVac.MultiSelect = false;
            this.gridCentroVac.Name = "gridCentroVac";
            this.gridCentroVac.ReadOnly = true;
            this.gridCentroVac.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.gridCentroVac.RowHeadersVisible = false;
            this.gridCentroVac.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle14.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(90)))));
            dataGridViewCellStyle14.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle14.ForeColor = System.Drawing.SystemColors.Info;
            dataGridViewCellStyle14.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            dataGridViewCellStyle14.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(175)))), ((int)(((byte)(188)))));
            dataGridViewCellStyle14.SelectionForeColor = System.Drawing.Color.Black;
            this.gridCentroVac.RowsDefaultCellStyle = dataGridViewCellStyle14;
            this.gridCentroVac.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridCentroVac.Size = new System.Drawing.Size(826, 175);
            this.gridCentroVac.TabIndex = 10;
            this.gridCentroVac.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridCentroVac_CellClick);
            // 
            // gridTipoCentro
            // 
            this.gridTipoCentro.AllowUserToAddRows = false;
            this.gridTipoCentro.AllowUserToDeleteRows = false;
            this.gridTipoCentro.AllowUserToResizeColumns = false;
            this.gridTipoCentro.AllowUserToResizeRows = false;
            this.gridTipoCentro.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridTipoCentro.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(34)))), ((int)(((byte)(51)))));
            this.gridTipoCentro.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.gridTipoCentro.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.gridTipoCentro.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle15.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle15.BackColor = System.Drawing.Color.SteelBlue;
            dataGridViewCellStyle15.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle15.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(215)))), ((int)(((byte)(225)))), ((int)(((byte)(242)))));
            dataGridViewCellStyle15.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            dataGridViewCellStyle15.SelectionBackColor = System.Drawing.SystemColors.ControlDark;
            dataGridViewCellStyle15.SelectionForeColor = System.Drawing.SystemColors.Desktop;
            dataGridViewCellStyle15.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.gridTipoCentro.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle15;
            this.gridTipoCentro.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.gridTipoCentro.EnableHeadersVisualStyles = false;
            this.gridTipoCentro.Location = new System.Drawing.Point(57, 70);
            this.gridTipoCentro.MultiSelect = false;
            this.gridTipoCentro.Name = "gridTipoCentro";
            this.gridTipoCentro.ReadOnly = true;
            this.gridTipoCentro.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.gridTipoCentro.RowHeadersVisible = false;
            this.gridTipoCentro.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle16.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(61)))), ((int)(((byte)(90)))));
            dataGridViewCellStyle16.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle16.ForeColor = System.Drawing.SystemColors.Info;
            dataGridViewCellStyle16.Padding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            dataGridViewCellStyle16.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(175)))), ((int)(((byte)(188)))));
            dataGridViewCellStyle16.SelectionForeColor = System.Drawing.Color.Black;
            this.gridTipoCentro.RowsDefaultCellStyle = dataGridViewCellStyle16;
            this.gridTipoCentro.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridTipoCentro.Size = new System.Drawing.Size(403, 121);
            this.gridTipoCentro.TabIndex = 12;
            this.gridTipoCentro.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridTipoCentro_CellClick);
            // 
            // lblTipoCentro
            // 
            this.lblTipoCentro.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTipoCentro.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(125)))), ((int)(((byte)(169)))));
            this.lblTipoCentro.Location = new System.Drawing.Point(56, 28);
            this.lblTipoCentro.Name = "lblTipoCentro";
            this.lblTipoCentro.Size = new System.Drawing.Size(237, 43);
            this.lblTipoCentro.TabIndex = 14;
            this.lblTipoCentro.Text = "Tipo de centros";
            this.lblTipoCentro.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblCentrosVac
            // 
            this.lblCentrosVac.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblCentrosVac.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCentrosVac.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(125)))), ((int)(((byte)(169)))));
            this.lblCentrosVac.Location = new System.Drawing.Point(56, 252);
            this.lblCentrosVac.Name = "lblCentrosVac";
            this.lblCentrosVac.Size = new System.Drawing.Size(454, 38);
            this.lblCentrosVac.TabIndex = 15;
            this.lblCentrosVac.Text = "Centros de vacunaciones disponibles";
            this.lblCentrosVac.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // btnEliminar
            // 
            this.btnEliminar.AllowAnimations = true;
            this.btnEliminar.AllowMouseEffects = true;
            this.btnEliminar.AllowToggling = false;
            this.btnEliminar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnEliminar.AnimationSpeed = 200;
            this.btnEliminar.AutoGenerateColors = false;
            this.btnEliminar.AutoRoundBorders = false;
            this.btnEliminar.AutoSizeLeftIcon = true;
            this.btnEliminar.AutoSizeRightIcon = true;
            this.btnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.btnEliminar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEliminar.BackgroundImage")));
            this.btnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.ButtonText = "Eliminar";
            this.btnEliminar.ButtonTextMarginLeft = 0;
            this.btnEliminar.ColorContrastOnClick = 45;
            this.btnEliminar.ColorContrastOnHover = 45;
            this.btnEliminar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges25.BottomLeft = true;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = true;
            borderEdges25.TopRight = true;
            this.btnEliminar.CustomizableEdges = borderEdges25;
            this.btnEliminar.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEliminar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEliminar.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEliminar.IconMarginLeft = 11;
            this.btnEliminar.IconPadding = 10;
            this.btnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEliminar.IconSize = 25;
            this.btnEliminar.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnEliminar.IdleBorderRadius = 1;
            this.btnEliminar.IdleBorderThickness = 1;
            this.btnEliminar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminar.IdleIconLeftImage = null;
            this.btnEliminar.IdleIconRightImage = null;
            this.btnEliminar.IndicateFocus = false;
            this.btnEliminar.Location = new System.Drawing.Point(571, 569);
            this.btnEliminar.Name = "btnEliminar";
            this.btnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.OnDisabledState.BorderRadius = 1;
            this.btnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnDisabledState.BorderThickness = 1;
            this.btnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.OnDisabledState.IconLeftImage = null;
            this.btnEliminar.OnDisabledState.IconRightImage = null;
            this.btnEliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminar.onHoverState.BorderRadius = 1;
            this.btnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.onHoverState.BorderThickness = 1;
            this.btnEliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminar.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminar.onHoverState.IconLeftImage = null;
            this.btnEliminar.onHoverState.IconRightImage = null;
            this.btnEliminar.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnEliminar.OnIdleState.BorderRadius = 1;
            this.btnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnIdleState.BorderThickness = 1;
            this.btnEliminar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminar.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnEliminar.OnIdleState.IconLeftImage = null;
            this.btnEliminar.OnIdleState.IconRightImage = null;
            this.btnEliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminar.OnPressedState.BorderRadius = 1;
            this.btnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnPressedState.BorderThickness = 1;
            this.btnEliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.OnPressedState.IconLeftImage = null;
            this.btnEliminar.OnPressedState.IconRightImage = null;
            this.btnEliminar.Size = new System.Drawing.Size(150, 39);
            this.btnEliminar.TabIndex = 31;
            this.btnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEliminar.TextMarginLeft = 0;
            this.btnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEliminar.UseDefaultRadiusAndThickness = true;
            this.btnEliminar.Click += new System.EventHandler(this.btnEliminar_Click);
            // 
            // btnModificar
            // 
            this.btnModificar.AllowAnimations = true;
            this.btnModificar.AllowMouseEffects = true;
            this.btnModificar.AllowToggling = false;
            this.btnModificar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnModificar.AnimationSpeed = 200;
            this.btnModificar.AutoGenerateColors = false;
            this.btnModificar.AutoRoundBorders = false;
            this.btnModificar.AutoSizeLeftIcon = true;
            this.btnModificar.AutoSizeRightIcon = true;
            this.btnModificar.BackColor = System.Drawing.Color.Transparent;
            this.btnModificar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModificar.BackgroundImage")));
            this.btnModificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.ButtonText = "Modificar";
            this.btnModificar.ButtonTextMarginLeft = 0;
            this.btnModificar.ColorContrastOnClick = 45;
            this.btnModificar.ColorContrastOnHover = 45;
            this.btnModificar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges26.BottomLeft = true;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = true;
            borderEdges26.TopRight = true;
            this.btnModificar.CustomizableEdges = borderEdges26;
            this.btnModificar.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnModificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModificar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModificar.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnModificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModificar.IconMarginLeft = 11;
            this.btnModificar.IconPadding = 10;
            this.btnModificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModificar.IconSize = 25;
            this.btnModificar.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnModificar.IdleBorderRadius = 1;
            this.btnModificar.IdleBorderThickness = 1;
            this.btnModificar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificar.IdleIconLeftImage = null;
            this.btnModificar.IdleIconRightImage = null;
            this.btnModificar.IndicateFocus = false;
            this.btnModificar.Location = new System.Drawing.Point(737, 569);
            this.btnModificar.Name = "btnModificar";
            this.btnModificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.OnDisabledState.BorderRadius = 1;
            this.btnModificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnDisabledState.BorderThickness = 1;
            this.btnModificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.OnDisabledState.IconLeftImage = null;
            this.btnModificar.OnDisabledState.IconRightImage = null;
            this.btnModificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.BorderRadius = 1;
            this.btnModificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.onHoverState.BorderThickness = 1;
            this.btnModificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificar.onHoverState.IconLeftImage = null;
            this.btnModificar.onHoverState.IconRightImage = null;
            this.btnModificar.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnModificar.OnIdleState.BorderRadius = 1;
            this.btnModificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnIdleState.BorderThickness = 1;
            this.btnModificar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificar.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnModificar.OnIdleState.IconLeftImage = null;
            this.btnModificar.OnIdleState.IconRightImage = null;
            this.btnModificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.BorderRadius = 1;
            this.btnModificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnPressedState.BorderThickness = 1;
            this.btnModificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.OnPressedState.IconLeftImage = null;
            this.btnModificar.OnPressedState.IconRightImage = null;
            this.btnModificar.Size = new System.Drawing.Size(150, 39);
            this.btnModificar.TabIndex = 30;
            this.btnModificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModificar.TextMarginLeft = 0;
            this.btnModificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModificar.UseDefaultRadiusAndThickness = true;
            this.btnModificar.Click += new System.EventHandler(this.btnModificar_Click);
            // 
            // btnCancelar
            // 
            this.btnCancelar.AllowAnimations = true;
            this.btnCancelar.AllowMouseEffects = true;
            this.btnCancelar.AllowToggling = false;
            this.btnCancelar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancelar.AnimationSpeed = 200;
            this.btnCancelar.AutoGenerateColors = false;
            this.btnCancelar.AutoRoundBorders = false;
            this.btnCancelar.AutoSizeLeftIcon = true;
            this.btnCancelar.AutoSizeRightIcon = true;
            this.btnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancelar.BackgroundImage")));
            this.btnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.ButtonText = "Cancelar";
            this.btnCancelar.ButtonTextMarginLeft = 0;
            this.btnCancelar.ColorContrastOnClick = 45;
            this.btnCancelar.ColorContrastOnHover = 45;
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.btnCancelar.CustomizableEdges = borderEdges27;
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancelar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancelar.IconMarginLeft = 11;
            this.btnCancelar.IconPadding = 10;
            this.btnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancelar.IconSize = 25;
            this.btnCancelar.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnCancelar.IdleBorderRadius = 1;
            this.btnCancelar.IdleBorderThickness = 1;
            this.btnCancelar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelar.IdleIconLeftImage = null;
            this.btnCancelar.IdleIconRightImage = null;
            this.btnCancelar.IndicateFocus = false;
            this.btnCancelar.Location = new System.Drawing.Point(405, 569);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.OnDisabledState.BorderRadius = 1;
            this.btnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnDisabledState.BorderThickness = 1;
            this.btnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.OnDisabledState.IconLeftImage = null;
            this.btnCancelar.OnDisabledState.IconRightImage = null;
            this.btnCancelar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancelar.onHoverState.BorderRadius = 1;
            this.btnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.onHoverState.BorderThickness = 1;
            this.btnCancelar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancelar.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelar.onHoverState.IconLeftImage = null;
            this.btnCancelar.onHoverState.IconRightImage = null;
            this.btnCancelar.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnCancelar.OnIdleState.BorderRadius = 1;
            this.btnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnIdleState.BorderThickness = 1;
            this.btnCancelar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelar.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnCancelar.OnIdleState.IconLeftImage = null;
            this.btnCancelar.OnIdleState.IconRightImage = null;
            this.btnCancelar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancelar.OnPressedState.BorderRadius = 1;
            this.btnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnPressedState.BorderThickness = 1;
            this.btnCancelar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.IconLeftImage = null;
            this.btnCancelar.OnPressedState.IconRightImage = null;
            this.btnCancelar.Size = new System.Drawing.Size(150, 39);
            this.btnCancelar.TabIndex = 32;
            this.btnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancelar.TextMarginLeft = 0;
            this.btnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancelar.UseDefaultRadiusAndThickness = true;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            // 
            // lblTotalCentros
            // 
            this.lblTotalCentros.AllowParentOverrides = false;
            this.lblTotalCentros.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.lblTotalCentros.AutoEllipsis = false;
            this.lblTotalCentros.AutoSize = false;
            this.lblTotalCentros.CursorType = null;
            this.lblTotalCentros.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalCentros.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(165)))), ((int)(((byte)(171)))), ((int)(((byte)(218)))));
            this.lblTotalCentros.Location = new System.Drawing.Point(61, 534);
            this.lblTotalCentros.Name = "lblTotalCentros";
            this.lblTotalCentros.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTotalCentros.Size = new System.Drawing.Size(329, 33);
            this.lblTotalCentros.TabIndex = 33;
            this.lblTotalCentros.Text = "TOTAL DE REGISTROS ENCONTRADOS: 0";
            this.lblTotalCentros.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTotalCentros.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnCancelarTipoC
            // 
            this.btnCancelarTipoC.AllowAnimations = true;
            this.btnCancelarTipoC.AllowMouseEffects = true;
            this.btnCancelarTipoC.AllowToggling = false;
            this.btnCancelarTipoC.AnimationSpeed = 200;
            this.btnCancelarTipoC.AutoGenerateColors = false;
            this.btnCancelarTipoC.AutoRoundBorders = false;
            this.btnCancelarTipoC.AutoSizeLeftIcon = true;
            this.btnCancelarTipoC.AutoSizeRightIcon = true;
            this.btnCancelarTipoC.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelarTipoC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelarTipoC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancelarTipoC.BackgroundImage")));
            this.btnCancelarTipoC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelarTipoC.ButtonText = "Cancelar";
            this.btnCancelarTipoC.ButtonTextMarginLeft = 0;
            this.btnCancelarTipoC.ColorContrastOnClick = 45;
            this.btnCancelarTipoC.ColorContrastOnHover = 45;
            this.btnCancelarTipoC.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges28.BottomLeft = true;
            borderEdges28.BottomRight = true;
            borderEdges28.TopLeft = true;
            borderEdges28.TopRight = true;
            this.btnCancelarTipoC.CustomizableEdges = borderEdges28;
            this.btnCancelarTipoC.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnCancelarTipoC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelarTipoC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelarTipoC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelarTipoC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancelarTipoC.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelarTipoC.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnCancelarTipoC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancelarTipoC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelarTipoC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancelarTipoC.IconMarginLeft = 11;
            this.btnCancelarTipoC.IconPadding = 10;
            this.btnCancelarTipoC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelarTipoC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelarTipoC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancelarTipoC.IconSize = 25;
            this.btnCancelarTipoC.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnCancelarTipoC.IdleBorderRadius = 3;
            this.btnCancelarTipoC.IdleBorderThickness = 1;
            this.btnCancelarTipoC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelarTipoC.IdleIconLeftImage = null;
            this.btnCancelarTipoC.IdleIconRightImage = null;
            this.btnCancelarTipoC.IndicateFocus = false;
            this.btnCancelarTipoC.Location = new System.Drawing.Point(185, 79);
            this.btnCancelarTipoC.Name = "btnCancelarTipoC";
            this.btnCancelarTipoC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelarTipoC.OnDisabledState.BorderRadius = 3;
            this.btnCancelarTipoC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelarTipoC.OnDisabledState.BorderThickness = 1;
            this.btnCancelarTipoC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelarTipoC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelarTipoC.OnDisabledState.IconLeftImage = null;
            this.btnCancelarTipoC.OnDisabledState.IconRightImage = null;
            this.btnCancelarTipoC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancelarTipoC.onHoverState.BorderRadius = 3;
            this.btnCancelarTipoC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelarTipoC.onHoverState.BorderThickness = 1;
            this.btnCancelarTipoC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCancelarTipoC.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelarTipoC.onHoverState.IconLeftImage = null;
            this.btnCancelarTipoC.onHoverState.IconRightImage = null;
            this.btnCancelarTipoC.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnCancelarTipoC.OnIdleState.BorderRadius = 3;
            this.btnCancelarTipoC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelarTipoC.OnIdleState.BorderThickness = 1;
            this.btnCancelarTipoC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnCancelarTipoC.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnCancelarTipoC.OnIdleState.IconLeftImage = null;
            this.btnCancelarTipoC.OnIdleState.IconRightImage = null;
            this.btnCancelarTipoC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancelarTipoC.OnPressedState.BorderRadius = 3;
            this.btnCancelarTipoC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelarTipoC.OnPressedState.BorderThickness = 1;
            this.btnCancelarTipoC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCancelarTipoC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancelarTipoC.OnPressedState.IconLeftImage = null;
            this.btnCancelarTipoC.OnPressedState.IconRightImage = null;
            this.btnCancelarTipoC.Size = new System.Drawing.Size(150, 39);
            this.btnCancelarTipoC.TabIndex = 36;
            this.btnCancelarTipoC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancelarTipoC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancelarTipoC.TextMarginLeft = 0;
            this.btnCancelarTipoC.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancelarTipoC.UseDefaultRadiusAndThickness = true;
            this.btnCancelarTipoC.Click += new System.EventHandler(this.btnCancelarTipoC_Click);
            // 
            // btnEliminarTipoC
            // 
            this.btnEliminarTipoC.AllowAnimations = true;
            this.btnEliminarTipoC.AllowMouseEffects = true;
            this.btnEliminarTipoC.AllowToggling = false;
            this.btnEliminarTipoC.AnimationSpeed = 200;
            this.btnEliminarTipoC.AutoGenerateColors = false;
            this.btnEliminarTipoC.AutoRoundBorders = false;
            this.btnEliminarTipoC.AutoSizeLeftIcon = true;
            this.btnEliminarTipoC.AutoSizeRightIcon = true;
            this.btnEliminarTipoC.BackColor = System.Drawing.Color.Transparent;
            this.btnEliminarTipoC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminarTipoC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEliminarTipoC.BackgroundImage")));
            this.btnEliminarTipoC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminarTipoC.ButtonText = "Eliminar";
            this.btnEliminarTipoC.ButtonTextMarginLeft = 0;
            this.btnEliminarTipoC.ColorContrastOnClick = 45;
            this.btnEliminarTipoC.ColorContrastOnHover = 45;
            this.btnEliminarTipoC.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges29.BottomLeft = true;
            borderEdges29.BottomRight = true;
            borderEdges29.TopLeft = true;
            borderEdges29.TopRight = true;
            this.btnEliminarTipoC.CustomizableEdges = borderEdges29;
            this.btnEliminarTipoC.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnEliminarTipoC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminarTipoC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminarTipoC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminarTipoC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEliminarTipoC.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEliminarTipoC.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnEliminarTipoC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEliminarTipoC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminarTipoC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEliminarTipoC.IconMarginLeft = 11;
            this.btnEliminarTipoC.IconPadding = 10;
            this.btnEliminarTipoC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEliminarTipoC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminarTipoC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEliminarTipoC.IconSize = 25;
            this.btnEliminarTipoC.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnEliminarTipoC.IdleBorderRadius = 3;
            this.btnEliminarTipoC.IdleBorderThickness = 1;
            this.btnEliminarTipoC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminarTipoC.IdleIconLeftImage = null;
            this.btnEliminarTipoC.IdleIconRightImage = null;
            this.btnEliminarTipoC.IndicateFocus = false;
            this.btnEliminarTipoC.Location = new System.Drawing.Point(185, 24);
            this.btnEliminarTipoC.Name = "btnEliminarTipoC";
            this.btnEliminarTipoC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminarTipoC.OnDisabledState.BorderRadius = 3;
            this.btnEliminarTipoC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminarTipoC.OnDisabledState.BorderThickness = 1;
            this.btnEliminarTipoC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminarTipoC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminarTipoC.OnDisabledState.IconLeftImage = null;
            this.btnEliminarTipoC.OnDisabledState.IconRightImage = null;
            this.btnEliminarTipoC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminarTipoC.onHoverState.BorderRadius = 3;
            this.btnEliminarTipoC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminarTipoC.onHoverState.BorderThickness = 1;
            this.btnEliminarTipoC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminarTipoC.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminarTipoC.onHoverState.IconLeftImage = null;
            this.btnEliminarTipoC.onHoverState.IconRightImage = null;
            this.btnEliminarTipoC.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnEliminarTipoC.OnIdleState.BorderRadius = 3;
            this.btnEliminarTipoC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminarTipoC.OnIdleState.BorderThickness = 1;
            this.btnEliminarTipoC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnEliminarTipoC.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnEliminarTipoC.OnIdleState.IconLeftImage = null;
            this.btnEliminarTipoC.OnIdleState.IconRightImage = null;
            this.btnEliminarTipoC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminarTipoC.OnPressedState.BorderRadius = 3;
            this.btnEliminarTipoC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminarTipoC.OnPressedState.BorderThickness = 1;
            this.btnEliminarTipoC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminarTipoC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEliminarTipoC.OnPressedState.IconLeftImage = null;
            this.btnEliminarTipoC.OnPressedState.IconRightImage = null;
            this.btnEliminarTipoC.Size = new System.Drawing.Size(150, 39);
            this.btnEliminarTipoC.TabIndex = 35;
            this.btnEliminarTipoC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEliminarTipoC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEliminarTipoC.TextMarginLeft = 0;
            this.btnEliminarTipoC.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEliminarTipoC.UseDefaultRadiusAndThickness = true;
            this.btnEliminarTipoC.Click += new System.EventHandler(this.btnEliminarTipoC_Click);
            // 
            // btnModificarTipoC
            // 
            this.btnModificarTipoC.AllowAnimations = true;
            this.btnModificarTipoC.AllowMouseEffects = true;
            this.btnModificarTipoC.AllowToggling = false;
            this.btnModificarTipoC.AnimationSpeed = 200;
            this.btnModificarTipoC.AutoGenerateColors = false;
            this.btnModificarTipoC.AutoRoundBorders = false;
            this.btnModificarTipoC.AutoSizeLeftIcon = true;
            this.btnModificarTipoC.AutoSizeRightIcon = true;
            this.btnModificarTipoC.BackColor = System.Drawing.Color.Transparent;
            this.btnModificarTipoC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificarTipoC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModificarTipoC.BackgroundImage")));
            this.btnModificarTipoC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificarTipoC.ButtonText = "Modificar";
            this.btnModificarTipoC.ButtonTextMarginLeft = 0;
            this.btnModificarTipoC.ColorContrastOnClick = 45;
            this.btnModificarTipoC.ColorContrastOnHover = 45;
            this.btnModificarTipoC.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges30.BottomLeft = true;
            borderEdges30.BottomRight = true;
            borderEdges30.TopLeft = true;
            borderEdges30.TopRight = true;
            this.btnModificarTipoC.CustomizableEdges = borderEdges30;
            this.btnModificarTipoC.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnModificarTipoC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificarTipoC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificarTipoC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificarTipoC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModificarTipoC.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModificarTipoC.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnModificarTipoC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModificarTipoC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificarTipoC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModificarTipoC.IconMarginLeft = 11;
            this.btnModificarTipoC.IconPadding = 10;
            this.btnModificarTipoC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModificarTipoC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificarTipoC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModificarTipoC.IconSize = 25;
            this.btnModificarTipoC.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnModificarTipoC.IdleBorderRadius = 3;
            this.btnModificarTipoC.IdleBorderThickness = 1;
            this.btnModificarTipoC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificarTipoC.IdleIconLeftImage = null;
            this.btnModificarTipoC.IdleIconRightImage = null;
            this.btnModificarTipoC.IndicateFocus = false;
            this.btnModificarTipoC.Location = new System.Drawing.Point(13, 79);
            this.btnModificarTipoC.Name = "btnModificarTipoC";
            this.btnModificarTipoC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificarTipoC.OnDisabledState.BorderRadius = 3;
            this.btnModificarTipoC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificarTipoC.OnDisabledState.BorderThickness = 1;
            this.btnModificarTipoC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificarTipoC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificarTipoC.OnDisabledState.IconLeftImage = null;
            this.btnModificarTipoC.OnDisabledState.IconRightImage = null;
            this.btnModificarTipoC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificarTipoC.onHoverState.BorderRadius = 3;
            this.btnModificarTipoC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificarTipoC.onHoverState.BorderThickness = 1;
            this.btnModificarTipoC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificarTipoC.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificarTipoC.onHoverState.IconLeftImage = null;
            this.btnModificarTipoC.onHoverState.IconRightImage = null;
            this.btnModificarTipoC.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnModificarTipoC.OnIdleState.BorderRadius = 3;
            this.btnModificarTipoC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificarTipoC.OnIdleState.BorderThickness = 1;
            this.btnModificarTipoC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnModificarTipoC.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnModificarTipoC.OnIdleState.IconLeftImage = null;
            this.btnModificarTipoC.OnIdleState.IconRightImage = null;
            this.btnModificarTipoC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificarTipoC.OnPressedState.BorderRadius = 3;
            this.btnModificarTipoC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificarTipoC.OnPressedState.BorderThickness = 1;
            this.btnModificarTipoC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificarTipoC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModificarTipoC.OnPressedState.IconLeftImage = null;
            this.btnModificarTipoC.OnPressedState.IconRightImage = null;
            this.btnModificarTipoC.Size = new System.Drawing.Size(150, 39);
            this.btnModificarTipoC.TabIndex = 34;
            this.btnModificarTipoC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModificarTipoC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModificarTipoC.TextMarginLeft = 0;
            this.btnModificarTipoC.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModificarTipoC.UseDefaultRadiusAndThickness = true;
            this.btnModificarTipoC.Click += new System.EventHandler(this.btnModificarTipoC_Click);
            // 
            // btnRegistrarTipoC
            // 
            this.btnRegistrarTipoC.AllowAnimations = true;
            this.btnRegistrarTipoC.AllowMouseEffects = true;
            this.btnRegistrarTipoC.AllowToggling = false;
            this.btnRegistrarTipoC.AnimationSpeed = 200;
            this.btnRegistrarTipoC.AutoGenerateColors = false;
            this.btnRegistrarTipoC.AutoRoundBorders = false;
            this.btnRegistrarTipoC.AutoSizeLeftIcon = true;
            this.btnRegistrarTipoC.AutoSizeRightIcon = true;
            this.btnRegistrarTipoC.BackColor = System.Drawing.Color.Transparent;
            this.btnRegistrarTipoC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnRegistrarTipoC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegistrarTipoC.BackgroundImage")));
            this.btnRegistrarTipoC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistrarTipoC.ButtonText = "Agregar";
            this.btnRegistrarTipoC.ButtonTextMarginLeft = 0;
            this.btnRegistrarTipoC.ColorContrastOnClick = 45;
            this.btnRegistrarTipoC.ColorContrastOnHover = 45;
            this.btnRegistrarTipoC.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges31.BottomLeft = true;
            borderEdges31.BottomRight = true;
            borderEdges31.TopLeft = true;
            borderEdges31.TopRight = true;
            this.btnRegistrarTipoC.CustomizableEdges = borderEdges31;
            this.btnRegistrarTipoC.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnRegistrarTipoC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistrarTipoC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistrarTipoC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistrarTipoC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRegistrarTipoC.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRegistrarTipoC.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnRegistrarTipoC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegistrarTipoC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegistrarTipoC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegistrarTipoC.IconMarginLeft = 11;
            this.btnRegistrarTipoC.IconPadding = 10;
            this.btnRegistrarTipoC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegistrarTipoC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegistrarTipoC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegistrarTipoC.IconSize = 25;
            this.btnRegistrarTipoC.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.btnRegistrarTipoC.IdleBorderRadius = 3;
            this.btnRegistrarTipoC.IdleBorderThickness = 1;
            this.btnRegistrarTipoC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnRegistrarTipoC.IdleIconLeftImage = null;
            this.btnRegistrarTipoC.IdleIconRightImage = null;
            this.btnRegistrarTipoC.IndicateFocus = false;
            this.btnRegistrarTipoC.Location = new System.Drawing.Point(13, 24);
            this.btnRegistrarTipoC.Name = "btnRegistrarTipoC";
            this.btnRegistrarTipoC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistrarTipoC.OnDisabledState.BorderRadius = 3;
            this.btnRegistrarTipoC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistrarTipoC.OnDisabledState.BorderThickness = 1;
            this.btnRegistrarTipoC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistrarTipoC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistrarTipoC.OnDisabledState.IconLeftImage = null;
            this.btnRegistrarTipoC.OnDisabledState.IconRightImage = null;
            this.btnRegistrarTipoC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegistrarTipoC.onHoverState.BorderRadius = 3;
            this.btnRegistrarTipoC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistrarTipoC.onHoverState.BorderThickness = 1;
            this.btnRegistrarTipoC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegistrarTipoC.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnRegistrarTipoC.onHoverState.IconLeftImage = null;
            this.btnRegistrarTipoC.onHoverState.IconRightImage = null;
            this.btnRegistrarTipoC.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.btnRegistrarTipoC.OnIdleState.BorderRadius = 3;
            this.btnRegistrarTipoC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistrarTipoC.OnIdleState.BorderThickness = 1;
            this.btnRegistrarTipoC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(22)))), ((int)(((byte)(40)))));
            this.btnRegistrarTipoC.OnIdleState.ForeColor = System.Drawing.Color.SteelBlue;
            this.btnRegistrarTipoC.OnIdleState.IconLeftImage = null;
            this.btnRegistrarTipoC.OnIdleState.IconRightImage = null;
            this.btnRegistrarTipoC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegistrarTipoC.OnPressedState.BorderRadius = 3;
            this.btnRegistrarTipoC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistrarTipoC.OnPressedState.BorderThickness = 1;
            this.btnRegistrarTipoC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegistrarTipoC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRegistrarTipoC.OnPressedState.IconLeftImage = null;
            this.btnRegistrarTipoC.OnPressedState.IconRightImage = null;
            this.btnRegistrarTipoC.Size = new System.Drawing.Size(150, 39);
            this.btnRegistrarTipoC.TabIndex = 37;
            this.btnRegistrarTipoC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegistrarTipoC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegistrarTipoC.TextMarginLeft = 0;
            this.btnRegistrarTipoC.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegistrarTipoC.UseDefaultRadiusAndThickness = true;
            this.btnRegistrarTipoC.Click += new System.EventHandler(this.btnRegistrarTipoC_Click);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(125)))), ((int)(((byte)(169)))));
            this.bunifuGroupBox1.BorderRadius = 2;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.btnEliminarTipoC);
            this.bunifuGroupBox1.Controls.Add(this.btnCancelarTipoC);
            this.bunifuGroupBox1.Controls.Add(this.btnRegistrarTipoC);
            this.bunifuGroupBox1.Controls.Add(this.btnModificarTipoC);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(125)))), ((int)(((byte)(169)))));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(466, 62);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(347, 129);
            this.bunifuGroupBox1.TabIndex = 38;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Controles asociados";
            // 
            // cboCamposFiltrar
            // 
            this.cboCamposFiltrar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(39)))), ((int)(((byte)(54)))));
            this.cboCamposFiltrar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboCamposFiltrar.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cboCamposFiltrar.ForeColor = System.Drawing.Color.Silver;
            this.cboCamposFiltrar.FormattingEnabled = true;
            this.cboCamposFiltrar.Location = new System.Drawing.Point(61, 318);
            this.cboCamposFiltrar.Name = "cboCamposFiltrar";
            this.cboCamposFiltrar.Size = new System.Drawing.Size(399, 29);
            this.cboCamposFiltrar.TabIndex = 40;
            // 
            // txtFiltrar
            // 
            this.txtFiltrar.AcceptsReturn = false;
            this.txtFiltrar.AcceptsTab = false;
            this.txtFiltrar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtFiltrar.AnimationSpeed = 200;
            this.txtFiltrar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFiltrar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFiltrar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(39)))), ((int)(((byte)(54)))));
            this.txtFiltrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFiltrar.BackgroundImage")));
            this.txtFiltrar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFiltrar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFiltrar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltrar.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltrar.BorderRadius = 2;
            this.txtFiltrar.BorderThickness = 1;
            this.txtFiltrar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFiltrar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltrar.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFiltrar.DefaultText = "";
            this.txtFiltrar.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(39)))), ((int)(((byte)(54)))));
            this.txtFiltrar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltrar.HideSelection = true;
            this.txtFiltrar.IconLeft = null;
            this.txtFiltrar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltrar.IconPadding = 5;
            this.txtFiltrar.IconRight = null;
            this.txtFiltrar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltrar.Lines = new string[0];
            this.txtFiltrar.Location = new System.Drawing.Point(466, 318);
            this.txtFiltrar.MaxLength = 32767;
            this.txtFiltrar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFiltrar.Modified = false;
            this.txtFiltrar.Multiline = false;
            this.txtFiltrar.Name = "txtFiltrar";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltrar.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFiltrar.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltrar.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(39)))), ((int)(((byte)(54)))));
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltrar.OnIdleState = stateProperties16;
            this.txtFiltrar.Padding = new System.Windows.Forms.Padding(3);
            this.txtFiltrar.PasswordChar = '\0';
            this.txtFiltrar.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtFiltrar.PlaceholderText = "Escriba aquí...";
            this.txtFiltrar.ReadOnly = false;
            this.txtFiltrar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFiltrar.SelectedText = "";
            this.txtFiltrar.SelectionLength = 0;
            this.txtFiltrar.SelectionStart = 0;
            this.txtFiltrar.ShortcutsEnabled = true;
            this.txtFiltrar.Size = new System.Drawing.Size(421, 29);
            this.txtFiltrar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtFiltrar.TabIndex = 39;
            this.txtFiltrar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFiltrar.TextMarginBottom = 0;
            this.txtFiltrar.TextMarginLeft = 3;
            this.txtFiltrar.TextMarginTop = 0;
            this.txtFiltrar.TextPlaceholder = "Escriba aquí...";
            this.txtFiltrar.UseSystemPasswordChar = false;
            this.txtFiltrar.WordWrap = true;
            this.txtFiltrar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txtFiltrar_KeyUp);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(165)))), ((int)(((byte)(171)))), ((int)(((byte)(218)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(61, 296);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(246, 25);
            this.bunifuLabel1.TabIndex = 41;
            this.bunifuLabel1.TabStop = false;
            this.bunifuLabel1.Text = "SELECCIONE UNA OPCIÓN";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnExpExcel
            // 
            this.btnExpExcel.AllowAnimations = true;
            this.btnExpExcel.AllowMouseEffects = true;
            this.btnExpExcel.AllowToggling = false;
            this.btnExpExcel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExpExcel.AnimationSpeed = 200;
            this.btnExpExcel.AutoGenerateColors = false;
            this.btnExpExcel.AutoRoundBorders = false;
            this.btnExpExcel.AutoSizeLeftIcon = true;
            this.btnExpExcel.AutoSizeRightIcon = true;
            this.btnExpExcel.BackColor = System.Drawing.Color.Transparent;
            this.btnExpExcel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(66)))), ((int)(((byte)(29)))));
            this.btnExpExcel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExpExcel.BackgroundImage")));
            this.btnExpExcel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExpExcel.ButtonText = " Exportar excel";
            this.btnExpExcel.ButtonTextMarginLeft = 0;
            this.btnExpExcel.ColorContrastOnClick = 45;
            this.btnExpExcel.ColorContrastOnHover = 45;
            this.btnExpExcel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges32.BottomLeft = true;
            borderEdges32.BottomRight = true;
            borderEdges32.TopLeft = true;
            borderEdges32.TopRight = true;
            this.btnExpExcel.CustomizableEdges = borderEdges32;
            this.btnExpExcel.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnExpExcel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExpExcel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExpExcel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExpExcel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExpExcel.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExpExcel.ForeColor = System.Drawing.Color.LightCyan;
            this.btnExpExcel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExpExcel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExpExcel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExpExcel.IconMarginLeft = 11;
            this.btnExpExcel.IconPadding = 10;
            this.btnExpExcel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExpExcel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExpExcel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExpExcel.IconSize = 25;
            this.btnExpExcel.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(219)))), ((int)(((byte)(136)))));
            this.btnExpExcel.IdleBorderRadius = 1;
            this.btnExpExcel.IdleBorderThickness = 1;
            this.btnExpExcel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(66)))), ((int)(((byte)(29)))));
            this.btnExpExcel.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExpExcel.IdleIconLeftImage")));
            this.btnExpExcel.IdleIconRightImage = null;
            this.btnExpExcel.IndicateFocus = false;
            this.btnExpExcel.Location = new System.Drawing.Point(737, 273);
            this.btnExpExcel.Name = "btnExpExcel";
            this.btnExpExcel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExpExcel.OnDisabledState.BorderRadius = 1;
            this.btnExpExcel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExpExcel.OnDisabledState.BorderThickness = 1;
            this.btnExpExcel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExpExcel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExpExcel.OnDisabledState.IconLeftImage = null;
            this.btnExpExcel.OnDisabledState.IconRightImage = null;
            this.btnExpExcel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(213)))), ((int)(((byte)(119)))));
            this.btnExpExcel.onHoverState.BorderRadius = 1;
            this.btnExpExcel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExpExcel.onHoverState.BorderThickness = 1;
            this.btnExpExcel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(84)))), ((int)(((byte)(16)))));
            this.btnExpExcel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExpExcel.onHoverState.IconLeftImage = null;
            this.btnExpExcel.onHoverState.IconRightImage = null;
            this.btnExpExcel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(219)))), ((int)(((byte)(136)))));
            this.btnExpExcel.OnIdleState.BorderRadius = 1;
            this.btnExpExcel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExpExcel.OnIdleState.BorderThickness = 1;
            this.btnExpExcel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(66)))), ((int)(((byte)(29)))));
            this.btnExpExcel.OnIdleState.ForeColor = System.Drawing.Color.LightCyan;
            this.btnExpExcel.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExpExcel.OnIdleState.IconLeftImage")));
            this.btnExpExcel.OnIdleState.IconRightImage = null;
            this.btnExpExcel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExpExcel.OnPressedState.BorderRadius = 1;
            this.btnExpExcel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExpExcel.OnPressedState.BorderThickness = 1;
            this.btnExpExcel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExpExcel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExpExcel.OnPressedState.IconLeftImage = null;
            this.btnExpExcel.OnPressedState.IconRightImage = null;
            this.btnExpExcel.Size = new System.Drawing.Size(150, 39);
            this.btnExpExcel.TabIndex = 42;
            this.btnExpExcel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExpExcel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExpExcel.TextMarginLeft = 0;
            this.btnExpExcel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExpExcel.UseDefaultRadiusAndThickness = true;
            this.btnExpExcel.Click += new System.EventHandler(this.btnExpExcel_Click);
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuSeparator1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(34)))), ((int)(((byte)(51)))));
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(125)))), ((int)(((byte)(169)))));
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(61, 220);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(826, 13);
            this.bunifuSeparator1.TabIndex = 43;
            // 
            // lblTotalRegistroTipoC
            // 
            this.lblTotalRegistroTipoC.AllowParentOverrides = false;
            this.lblTotalRegistroTipoC.AutoEllipsis = false;
            this.lblTotalRegistroTipoC.AutoSize = false;
            this.lblTotalRegistroTipoC.CursorType = null;
            this.lblTotalRegistroTipoC.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalRegistroTipoC.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(165)))), ((int)(((byte)(171)))), ((int)(((byte)(218)))));
            this.lblTotalRegistroTipoC.Location = new System.Drawing.Point(61, 197);
            this.lblTotalRegistroTipoC.Name = "lblTotalRegistroTipoC";
            this.lblTotalRegistroTipoC.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTotalRegistroTipoC.Size = new System.Drawing.Size(329, 26);
            this.lblTotalRegistroTipoC.TabIndex = 44;
            this.lblTotalRegistroTipoC.Text = "TOTAL DE REGISTROS ENCONTRADOS: 0";
            this.lblTotalRegistroTipoC.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTotalRegistroTipoC.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmCentro
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(34)))), ((int)(((byte)(51)))));
            this.ClientSize = new System.Drawing.Size(950, 631);
            this.Controls.Add(this.lblTotalRegistroTipoC);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.btnExpExcel);
            this.Controls.Add(this.cboCamposFiltrar);
            this.Controls.Add(this.txtFiltrar);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.lblTotalCentros);
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.btnEliminar);
            this.Controls.Add(this.btnModificar);
            this.Controls.Add(this.gridCentroVac);
            this.Controls.Add(this.gridTipoCentro);
            this.Controls.Add(this.lblCentrosVac);
            this.Controls.Add(this.lblTipoCentro);
            this.Controls.Add(this.bunifuGroupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmCentro";
            this.Text = "frmCentro";
            this.Load += new System.EventHandler(this.FrmCentroLoad);
            ((System.ComponentModel.ISupportInitialize)(this.gridCentroVac)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridTipoCentro)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

		}
		private System.Windows.Forms.DataGridView gridTipoCentro;
		private System.Windows.Forms.DataGridView gridCentroVac;
        private System.Windows.Forms.Label lblTipoCentro;
        private System.Windows.Forms.Label lblCentrosVac;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancelar;
        private Bunifu.UI.WinForms.BunifuLabel lblTotalCentros;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancelarTipoC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEliminarTipoC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModificarTipoC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRegistrarTipoC;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.ComboBox cboCamposFiltrar;
        private Bunifu.UI.WinForms.BunifuTextBox txtFiltrar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExpExcel;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel lblTotalRegistroTipoC;
    }
}
